### ISSUE TITLE
Inconsistency between manuscript/paper and code output

### ISSUE THREAD

**Issue by silver-fox-9244** [doan-van/S-SOM-V1#1]
Hi Quan-Van

I have recently attempted to implement the S-SOM diagnostic using the S-SOM-V1 scripts. While I do get output, it seems to be considerably inconsistent with the figures in the article. I've attached two examples from the runs using the provided scripts to be compared with Figures 4 (DJF) and A2 (MAM) in the article. I was therefore wondering if there is a second version of this code, and whether or not the **pmsl.nc** data is already interpolated to the scalable equal area grid? 

![fig_som_com_rev_DJF](https://github.com/doan-van/S-SOM-V1/assets/60083436/7cc45a7d-c6df-436b-969b-6acbfdfe984b)
![fig_som_com_rev_MAM](https://github.com/doan-van/S-SOM-V1/assets/60083436/e77891a0-69cc-42cd-a781-1f883b7d8c1b)

**Comment by doan-van** [comment]
This is because SOM, like many clustering methods, use randomized initial weights. Thus, each time, the results look slightly different. Or there is change in orders of clusters (i.e., pattern 1 could be 4 in different runs, it does not matter much if the patterns still there). 
If you use fixed initial weights of node (by change code in sompy.py) I believe that you will have completely same results with different runs.

Related with this issue in data clustering, you can read more in our paper:
https://gmd.copernicus.org/articles/16/2215/2023/

**Comment by silver-fox-9244** [comment]
Okay, that makes sense now. Thank you very much for the swift response, and for making these tools available.
